Review my codes
Shubh-Dev/Hello-world pull request #2
Opened 2022-02-08 17:20 UTC by Shubh-Dev

Descriptive commit message
Description of the project in readme file
Linters files
ignore file

2022-02-08 17:32 UTC, ShoiraTa requested changes
Hi @Shubh-Dev ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

- [ ] Pull Request should have a descriptive title telling you what changes are inside. Currently it is called  Please edit the pull request and add title. Hint: you can called `Review my codes` it does not tell anything about the feature you developed you can name it `Hello Microverse project` 😉 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-08 17:32 UTC, ShoiraTa commented on .github/workflow/linters.yml
> +on: pull_request
- [ ] As you have noticed, linters tests are not working for this project, this is happening because directory is misspelled, currently it is `workflow`, please rename it to `workflows`  an then all tests will run☘️

2022-02-08 17:32 UTC, ShoiraTa commented on .gitignore
> +node_modules/
- [ ] great job adding `node_modules/` 👍🏻 👍🏻

2022-02-08 17:32 UTC, ShoiraTa commented on README.md
> +This project is created by a Microverse student to apply and play with linters.
- [ ] This `readme` looks very plain without cool styled headings and paragraphs 😄. Please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project. Or you can check how to format `.md` documents and apply it on your `readme` 😉

2022-02-09 08:17 UTC, Shubh-Dev commented on .github/workflow/linters.yml
> +on: pull_request
Hi ShoiraTa,
Thank you so much for your feedback and your guidance.
I followed your instructions and made the necessary changes to the project.
Please have a look and guide me through the next steps.

2022-02-09 08:18 UTC, Shubh-Dev commented on .gitignore
> +node_modules/
Thank you :-)

2022-02-09 08:19 UTC, Shubh-Dev commented on README.md
> +This project is created by a Microverse student to apply and play with linters.
I added some styling to the file. Let me know if It is ok.

2022-02-09 08:35 UTC, Shubh-Dev commented on .gitignore
> +node_modules/
I had a question.. Do I need to submit my project again in the Microverse dashboard after this correction ?

2022-02-09 09:45 UTC, thecodechaser approved these changes
## Hi @Shubh-Dev 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Suggestions
- [ ]  Great job providing the description for the Pull Request, You can improve it more if you can update it by telling what changes are inside.  You can use bullet points
- Added HTML file
- Added CSS file
- Implemented XYZ


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-09 09:57 UTC, merged